from rest_framework import serializers
from movielens_app.models import Movie, Ratings, Tags

# Using this as our main serializer class 
class MovieSerializer(serializers.ModelSerializer):
    genres = serializers.SerializerMethodField()
    tags = serializers.SerializerMethodField()

    def get_genres(self, instance):
        return instance.genres.split("|")
    
    def get_tags(self, instance: Movie):
        # Get all tags related to the movie
        tags = instance.tags.all()
        return ", ".join(tag.tag for tag in tags)

    class Meta:
        model = Movie
        #fields = ["title", "genres", "tags"] # removed the movie, because it's autogenerated by the model
        fields = ["movieId", "title", "genres", "tags"]

class SubmitRatingSerializer(serializers.ModelSerializer):
    class Meta:
        model = Ratings
        fields = ["rating"]

class RatingSerializer(serializers.ModelSerializer):
    class Meta:
        model = Ratings
        fields = ["userId", "movieId", "rating", "timestamp"]

class TagSerializer(serializers.ModelSerializer):
    class Meta:
        model = Tags
        fields = ["userId", "movie", "tag", "timestamp"]
